docs: Update API documentation URL
koishijs/koishi-plugin-adapter-onebot pull request #14
Opened 2024-01-30 10:49 UTC by SaarChaffee

2024-01-30 14:24 UTC, shigma requested changes

2024-01-30 14:24 UTC, shigma commented on readme.md
> +你可以通过 `bot.internal` 或 `session.onebot` 访问内部 API，参见 [官方 API 文档](https://github.com/botuniverse/onebot-11/blob/master/api/README.md)。
```suggestion
你可以通过 `bot.internal` 或 `session.onebot` 访问内部 API，参见 [访问内部接口](https://koishi.chat/zh-CN/guide/adapter/bot.html#internal-access)。
```

2024-01-30 18:45 UTC, shigma approved these changes

2024-01-30 18:45 UTC, merged

2024-01-30 18:46 UTC, shigma commented
才发现你上面还有个链接没修……

2024-01-31 00:57 UTC, SaarChaffee commented
> 才发现你上面还有个链接没修……

不好意思，我待会全部检查一遍