fix: group message sendability when using plugin server-satori
koishijs/koishi-plugin-adapter-onebot pull request #20
Opened 2024-02-19 19:00 UTC by lgc2333

#18

2024-02-20 03:00 UTC, ilharp requested changes
不要用 `this.channelId.startsWith('private:')` 或 `this.session.isDirect`

- 前者是创建 Session 时才应该使用的方法，在 Session 外部可以调用 Session 的封装来判断
- 后者已被 Satori 协议标准的 `session.event.channel.type` 替代，`session.event.channel.type` 会在 Satori 协议中传输而 `isDirect` 不会

`session.event.channel.type` 目前没有在创建 Session 时填充，需要在 `prepare()` 方法中做五件事来填充，可以看这里：

https://github.com/satorijs/satori/pull/196#issuecomment-1953407085

直接在当前类里新写 `async prepare() {}` 即可，Satori 会自动调用

写完以后记得本地测试一下

2024-02-20 05:07 UTC, lgc2333 commented on src/bot/message.ts
> +export const PRIVATE_PFX = 'private:'
个人觉得提出来比较好

2024-02-21 03:12 UTC, ilharp commented on src/bot/message.ts
> +export const PRIVATE_PFX = 'private:'
也行

2024-02-21 03:13 UTC, ilharp approved these changes

2024-02-21 18:12 UTC, XxLittleCxX requested changes

2024-02-21 18:12 UTC, XxLittleCxX commented on src/bot/message.ts
> +    this.session.isDirect = channel.type === Universal.Channel.Type.DIRECT
这个要设吗，core 里面的 isDirect 的 setter 和这个作用一样吧

2024-02-21 18:12 UTC, XxLittleCxX commented on src/bot/message.ts
> +      : this.session.event.channel.type === Universal.Channel.Type.DIRECT
同上

2024-02-21 18:12 UTC, XxLittleCxX commented on src/bot/message.ts
> +    session.messageId = this.session.event.channel.type === Universal.Channel.Type.DIRECT
改成 `this.session.isDirect` 会不会好理解一点，不改也行...吧？

2024-02-21 18:23 UTC, lgc2333 commented on src/bot/message.ts
> +    this.session.isDirect = channel.type === Universal.Channel.Type.DIRECT
不知道，il让这样改的

2024-02-21 18:23 UTC, lgc2333 commented on src/bot/message.ts
> +      : this.session.event.channel.type === Universal.Channel.Type.DIRECT
il不让用isDirect

2024-02-22 02:52 UTC, ilharp commented on src/bot/message.ts
> +    this.session.isDirect = channel.type === Universal.Channel.Type.DIRECT
> 这个要设吗，core 里面的 isDirect 的 setter 和这个作用一样吧

在哪里

2024-02-22 02:54 UTC, ilharp commented on src/bot/message.ts
> +      : this.session.event.channel.type === Universal.Channel.Type.DIRECT
`this.session.event.channel.type` 已经替代了 `this.session.isDirect` 的职能，并对未来可能出现的「语音文字频道」和「私聊语音文字频道」等功能有良好支持。`this.session.isDirect` 只在有限场景下有支持。

2024-02-22 05:01 UTC, XxLittleCxX commented on src/bot/message.ts
> +    this.session.isDirect = channel.type === Universal.Channel.Type.DIRECT
https://github.com/satorijs/satori/blob/3224f5d491e9330c76ef3006665aea30f18e63e4/packages/core/src/session.ts#L63

2024-02-22 12:59 UTC, shigma commented on src/bot/message.ts
> +      : this.session.event.channel.type === Universal.Channel.Type.DIRECT
问题是，如果未来有「语音文字频道」和「私聊语音文字频道」，这里是不是还得改一遍？（不然依然不支持）

2024-02-22 12:59 UTC, shigma commented on src/bot/message.ts
> +    this.session.isDirect = channel.type === Universal.Channel.Type.DIRECT
isDirect 是 accessor，已经设置了 type 的情况下不应该手动设置。

应当仅同步 type 本身。

2024-02-24 03:06 UTC, ilharp commented on src/bot/message.ts
> +      : this.session.event.channel.type === Universal.Channel.Type.DIRECT
是，依然得改。但如果使用 `this.session.isDirect` 则无论如何改动也无法实现。

2024-02-24 03:10 UTC, ilharp approved these changes

2024-02-24 03:55 UTC, shigma requested changes

2024-02-24 03:55 UTC, shigma commented on src/bot/message.ts
> +    this.session.isDirect = channel.type === Universal.Channel.Type.DIRECT
```suggestion
```

将 isDirect 设置为 false 会覆写掉 type，建议删掉此行。

2024-02-24 04:08 UTC, lgc2333 commented on src/bot/message.ts
> +    this.session.isDirect = channel.type === Universal.Channel.Type.DIRECT
https://github.com/koishijs/koishi-plugin-adapter-onebot/pull/20/commits/dafc73574606538a614e5600ac9153f275250251

2024-02-24 05:22 UTC, shigma approved these changes

2024-02-24 05:22 UTC, merged