feat: support napcat
koishijs/koishi-plugin-adapter-onebot pull request #51
Opened 2024-08-30 05:48 UTC by LingLambda

add API:
setQqAvatar
setOnlineStatus
getGroupFileCount
getGroupFileList
setGroupFileFolder
delGroupFile
delGroupFileFolder

2024-09-01 16:37 UTC, shigma requested changes

2024-09-01 16:37 UTC, shigma commented on src/types.ts
> +Internal.define("set_qq_avatar", "file")
麻烦双引号改一下单引号，下同。

2024-09-02 00:43 UTC, LingLambda reviewed
感谢,已更改

2024-09-02 06:05 UTC, shigma commented on src/types.ts
> +  setOnlineStatus(status: string, extStatus: string, batteryStatus: string):Promise<void>
```suggestion
  setOnlineStatus(status: string, extStatus: string, batteryStatus: string): Promise<void>
```

2024-09-02 06:05 UTC, shigma approved these changes

2024-09-02 06:05 UTC, merged

2024-09-02 06:06 UTC, shigma commented
预计明后天发版。

2024-09-03 14:35 UTC, idranme commented
NapCat 已将群文件相关 API 更换为 Go-CQHTTP 标准

2024-09-03 15:27 UTC, idranme commented
> 需要全部回退吗？还是有可以保留的部分？

get_group_file_count → get_group_file_system_info
get_group_file_list → get_group_root_files
set_group_file_folder → create_group_file_folder
del_group_file → delete_group_file
del_group_file_folder → delete_group_file_folder

可以保留：
setQqAvatar
setOnlineStatus